name: Run EPG Merger and Deploy

on:
  schedule:
    - cron: '0 9 * * *'     # Every day at 2:00 AM Mexico time (UTC-7)
  workflow_dispatch:        # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          submodules: true   # Needed to pull iptv-org submodule

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Grab EPG for Sky Sports from iptv-org
        run: |
          cd iptv-org
          npm install
          npm run grab -- --days=3 --channels=custom-sky.xml
          cd ..

      - name: Run EPG merger script
        run: python epg_merger.py

      - name: Deploy guia-izzi.xml to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone --single-branch --branch gh-pages https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} gh-pages
          cp guia-izzi.xml gh-pages/
          cd gh-pages
          git add guia-izzi.xml
          git commit -m "Update EPG $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
