name: Run EPG Merger and Deploy

on:
  schedule:
    - cron: '0 */12 * * *'   # Every 12 hours
  workflow_dispatch:         # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run EPG script
        run: python epg_merger.py

      - name: Deploy guia-izzi.xml to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone --single-branch --branch gh-pages https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} gh-pages
          cp guia-izzi.xml gh-pages/
          cd gh-pages
          git add guia-izzi.xml
          git commit -m "Update EPG $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
